/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "Pin_Button_4_aliases.h"
#include "Pin_Button_4.h"
#include "Pin_Button_3_aliases.h"
#include "Pin_Button_3.h"
#include "isr_button_press.h"
#include "Pin_Button_2_aliases.h"
#include "Pin_Button_2.h"
#include "Pin_Button_1_aliases.h"
#include "Pin_Button_1.h"
#include "SevenSeg_Reg.h"
#include "Pin_7_seg_A_aliases.h"
#include "Pin_7_seg_A.h"
#include "Pin_7_seg_B_aliases.h"
#include "Pin_7_seg_B.h"
#include "Pin_7_seg_C_aliases.h"
#include "Pin_7_seg_C.h"
#include "Pin_7_seg_D_aliases.h"
#include "Pin_7_seg_D.h"
#include "Pin_7_seg_E_aliases.h"
#include "Pin_7_seg_E.h"
#include "Pin_7_seg_F_aliases.h"
#include "Pin_7_seg_F.h"
#include "Pin_7_seg_G_aliases.h"
#include "Pin_7_seg_G.h"
#include "Pin_7_seg_DP_aliases.h"
#include "Pin_7_seg_DP.h"
#include "Pin_Sel_A_aliases.h"
#include "Pin_Sel_A.h"
#include "UART_LOG.h"
#include "isr_start_game.h"
#include "RGB_PWM_red.h"
#include "Yellow_Led_aliases.h"
#include "Yellow_Led.h"
#include "Green_Led_aliases.h"
#include "Green_Led.h"
#include "Red_Led_aliases.h"
#include "Red_Led.h"
#include "RGB_PWM_green.h"
#include "RGB_PWM_blue.h"
#include "PWM_Clock.h"
#include "RGB_R_aliases.h"
#include "RGB_R.h"
#include "RGB_G_aliases.h"
#include "RGB_G.h"
#include "RGB_B_aliases.h"
#include "RGB_B.h"
#include "PWM_Red.h"
#include "PWM_Green.h"
#include "PWM_Yellow.h"
#include "timer_clock.h"
#include "Timer_3secs.h"
#include "isr_3secs.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

